# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-22 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cidade',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nm_cidade', models.CharField(blank=True, max_length=50, verbose_name='Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('codcliente', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(blank=True, max_length=90)),
                ('email', models.EmailField(blank=True, max_length=90)),
                ('bairro', models.CharField(blank=True, max_length=90)),
                ('cidade', models.CharField(blank=True, max_length=90)),
                ('estado', models.CharField(blank=True, max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='colecao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('colecao', models.CharField(max_length=90)),
                ('descricao', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='costureira',
            fields=[
                ('cod_costureira', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=90)),
                ('cpf', models.CharField(blank=True, max_length=90)),
                ('endereco', models.CharField(blank=True, max_length=90)),
                ('num', models.CharField(blank=True, max_length=90)),
                ('complemento', models.CharField(blank=True, max_length=90)),
                ('bairro', models.CharField(blank=True, max_length=90)),
                ('cep', models.CharField(blank=True, max_length=90)),
                ('ddd1', models.CharField(blank=True, max_length=4, verbose_name='DDD')),
                ('fone1', models.CharField(blank=True, max_length=15, verbose_name='Telefone Principal')),
                ('ddd2', models.CharField(blank=True, max_length=4, verbose_name='DDD')),
                ('fone2', models.CharField(blank=True, max_length=15, verbose_name='Tefone de apoio')),
                ('contato', models.CharField(blank=True, max_length=90)),
                ('email', models.EmailField(blank=True, max_length=90)),
                ('banco', models.CharField(blank=True, max_length=90)),
                ('tipoconta', models.CharField(blank=True, max_length=90)),
                ('agencia', models.CharField(blank=True, max_length=90)),
                ('numeroconta', models.CharField(blank=True, max_length=90, verbose_name='Número da conta')),
                ('status', models.CharField(blank=True, max_length=25)),
                ('obs', models.CharField(blank=True, max_length=90)),
                ('cidade', models.ForeignKey(blank=True, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='cadastro.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nm_estado', models.CharField(blank=True, max_length=50, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='itinerario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nr_itinerario', models.IntegerField()),
                ('ds_itinerario', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_servico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_servico', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='costureira',
            name='estado',
            field=models.ForeignKey(blank=True, default=0, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='cadastro.estado'),
        ),
        migrations.AddField(
            model_name='costureira',
            name='rota',
            field=models.ForeignKey(blank=True, max_length=20, on_delete=django.db.models.deletion.CASCADE, to='cadastro.itinerario'),
        ),
    ]
