# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-27 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20171227_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='abatimento',
            name='finalizado',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
