# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-22 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_pedido', models.IntegerField(default=0)),
                ('num_ordem', models.CharField(blank=True, max_length=90)),
                ('quant1', models.CharField(blank=True, max_length=90)),
                ('dt_saida', models.DateField(blank=True)),
                ('dt_entrada', models.DateField(blank=True)),
                ('num_ficha', models.CharField(blank=True, max_length=90)),
                ('valor1', models.CharField(blank=True, max_length=90)),
                ('total1', models.CharField(blank=True, max_length=90)),
                ('obs', models.CharField(blank=True, max_length=90)),
                ('finalizado', models.CharField(blank=True, max_length=90)),
                ('colecao', models.CharField(blank=True, max_length=90)),
                ('desconto', models.CharField(blank=True, max_length=90)),
                ('quantidadedesconto', models.CharField(blank=True, max_length=90)),
                ('valorunitariodesconto', models.CharField(blank=True, max_length=90)),
                ('totaldesconto', models.CharField(blank=True, max_length=90)),
                ('cliente', models.ForeignKey(blank=True, max_length=90, on_delete=django.db.models.deletion.CASCADE, to='cadastro.cliente')),
                ('nome_costureira', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.costureira')),
                ('tipo_servico', models.ForeignKey(blank=True, default=0, max_length=40, on_delete=django.db.models.deletion.CASCADE, to='cadastro.tipo_servico')),
            ],
        ),
    ]
