# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-12-27 03:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_auto_20171226_1406'),
    ]

    operations = [
        migrations.DeleteModel(
            name='abatimento',
        ),
    ]
