# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-29 04:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_servicosreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicos',
            name='desconto',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='quantidadedesconto',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='totaldesconto',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='valorunitariodesconto',
        ),
        migrations.AddField(
            model_name='servicos',
            name='dt_faturado',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 12, 29, 4, 5, 58, 178780, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='servicos',
            name='faturado',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
    ]
