# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-29 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_auto_20171229_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='dt_faturado',
            field=models.DateField(blank=True),
        ),
    ]
