# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-29 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0007_auto_20171229_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='faturamento',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('servicos.servicos',),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='cliente',
            field=models.ForeignKey(max_length=90, on_delete=django.db.models.deletion.CASCADE, to='cadastro.cliente'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='colecao',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='dt_entrada',
            field=models.DateField(verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='dt_faturado',
            field=models.DateField(verbose_name='Faturado Mês'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='dt_saida',
            field=models.DateField(verbose_name='Data de Saída'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='nome_costureira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.costureira'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='num_ficha',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='num_ordem',
            field=models.CharField(max_length=90, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='obs',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='quant1',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='tipo_servico',
            field=models.ForeignKey(max_length=40, on_delete=django.db.models.deletion.CASCADE, to='cadastro.tipo_servico'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='total1',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='valor1',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
